<?php

/**
 * PlugindhChangeRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugindhChangeRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugindhChangeRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugindhChangeRequest');
    }
}